version: "3.7"
services:
  app:
    container_name: app-ldap-gerenciador
    image: ldap-gerenciador
    build:
      args:
        user: dockerd
        uid: 1000
      context: ./php-fpm
    restart: unless-stopped
    working_dir: /var/www/projeto
    volumes:
      - ./projeto:/var/www/projeto
    networks:
      - backend
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    container_name: nginx-ldap-gerenciador
    user: root
    ports:
      - 8021:80
    volumes:
      - ./projeto:/var/www/projeto
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - backend
  db:
    image: mysql
    container_name: db-ldap-gerenciador
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ldap
      MYSQL_USER: ldap
      MYSQL_PASSWORD: ldap

networks:
  backend:
    driver: bridge
volumes:
  db_data:
    driver: local
